# Denite
[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = 'call config#denite#hook_add()'
hook_source = 'call config#denite#hook_source()'
hook_post_source = 'call config#denite#hook_post_source()'
depends = ['neoyank.vim', 'neomru.vim']

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

# File Explorer
[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = 'call config#defx#hook_add()'
hook_source = 'call config#defx#hook_source()'
depends = ['defx-icons', 'defx-git']

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'


# Input Support
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
 
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# rev = 'release'
# on_event = 'InsertEnter'
# merged = '0'
# hook_source = 'call config#coc#hook_source()'
