# Vim Package Manager
[[plugins]]
repo = 'Shougo/dein.vim'

# System
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'roxma/nvim-yarp'

# Colorscheme
[[plugins]]
repo = 'dracula/vim'

# StatusLine
[[plugins]]
repo =  'itchyny/lightline.vim'
hook_add = 'call config#lightline#hook_add()'

# [[plugins]]
# repo = 'maximbaz/lightline-ale'
# depends = ['lightline.vim']
# hook_add = 'call config#lightline_ale#hook_add()'

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_add = 'call config#ale#hook_add()'