# Vim Package Manager
[[plugins]]
repo = 'Shougo/dein.vim'


# System
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'Shougo/context_filetype.vim'


# Colorscheme
[[plugins]]
repo = 'dracula/vim'


# Nerdfont
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'


# StatusLine
[[plugins]]
repo =  'itchyny/lightline.vim'
hook_add = 'call config#lightline#hook_add()'

[[plugins]]
repo = 'maximbaz/lightline-ale'
hook_add = 'call config#lightline#ale_hook_add()'


# LSP
# [[plugins]]
# repo = 'neoclide/coc.nvim'
# rev = 'release'
# on_event = 'InsertEnter'
# merged = '0'
# hook_source = 'call config#coc#hook_source()'

# Lint Engine
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'call config#ale#hook_add()'

[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'call config#caw#hook_add()'


# Git
[[plugins]]
repo = 'airblade/vim-gitgutter'
