# Vim Package Manager
[[plugins]]
repo = 'Shougo/dein.vim'

# Layout
## Icons
[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

## Status Bar
[[plugins]]
repo =  'itchyny/lightline.vim'
hook_add = 'call config#lightline#hook_add()'

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim']
hook_add = 'call config#lightline_ale#hook_add()'

[[plugins]]
repo = 'itchyny/vim-gitbranch'

## Filer
[[plugins]]
repo = 'Shougo/defx.nvim'
on_cmd = ['Defx']
hook_add = 'call config#defx#hook_add()'
hook_source = 'call config#defx#hook_source()'
depends = ['defx-icons', 'defx-git']

[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = ['vim-devicons']

[[plugins]]
repo = 'kristijanhusak/defx-git'

# Others
## Git
[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

## Input Support
[[plugins]]
repo = 'tyru/caw.vim'
hook_add = 'call config#caw#hook_add()'

## System
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = 'call config#ale#hook_add()'

## Colorscheme
[[plugins]]
repo = 'dracula/vim'
